### ISSUE TITLE
Header navigation hidden on Safari

### ISSUE THREAD

**Issue by dhritzkiv** [rollup/rollupjs.org#109]
Safari TP R47
![screen shot 2018-01-17 at 10 06 58](https://user-images.githubusercontent.com/1349865/35049517-447a82b6-fb6e-11e7-839f-19cbc092d21b.png)

Chrome
![screen shot 2018-01-17 at 10 07 56](https://user-images.githubusercontent.com/1349865/35049528-5226599e-fb6e-11e7-8821-c771d6a58d8c.png)

**Comment by Rich-Harris** [comment]
Thanks — looks like Safari interprets 'overflow: auto' differently to other browsers... now fixed
