### ISSUE TITLE
Thanks a million

### ISSUE THREAD

**Issue by kinday** [rollup/rollupjs.org#127]
To owner and all contributors, who wrote such a fantastic documentation, thank you!

I was holding a workshop in my company today so the team can start using Rollup and the practical part went much smoother than I expected. People were doing things so fast, that I needed to come up with new tasks _on the go_.

Eight people of various experience, who heard about Rollup for the first time, were able to set up Rollup so it will produce ES modules with code being compiled down to ES5 in 30-40 minutes.

Thanks for the great documentation and helpful warnings produced by CLI app.

**Comment by Rich-Harris** [comment]
On behalf of everyone who has contributed to the docs, thank you for the kind words! Documentation is a difficult and (usually 😀) thankless task, so it's warmly appreciated.
