### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mysticatea** [rollup/rollupjs.org#134]
![image](https://user-images.githubusercontent.com/1937871/40278691-e7b2976c-5c70-11e8-90bc-7eb61ea1ca1b.png)

**Comment by lukastaegert** [comment]
Sorry for the inconvenience. @Rich-Harris is working on a fix at #135 but it will take a little while longer due to time-constraints on his side.

**Comment by lukastaegert** [comment]
Should be fixed for now, sorry for the long wait.
