### ISSUE TITLE
Cant use npm link

### ISSUE THREAD

**Issue by matiasmenker** [rollup/rollupjs.org#141]
Hi i will describe the problem:

We have a react library of component called **frontend-component** (so original) with storybook and the rollup.js

We import this library on the app project called **frontend-app** so:

frontend-app:
       dependencies -> frontend-component

I want to make a link between both projects, for update something on the frontend-component and see the change on the app, it will possible?

I try to use but doesn't work, any persona have some idea how its works?

**Comment by lukastaegert** [comment]
For support, please visit https://is.gd/rollup_chat
