### ISSUE TITLE
Update babel setup guide for Babel 7

### ISSUE THREAD

**Issue by tmcw** [rollup/rollupjs.org#152]
Babel 7's the new stablebabel, and... the guide needs some updates to that effect.

Some changes:

- `"plugins": ["external-helpers"]` should probably be removed per [this comment](https://github.com/rollup/rollup-plugin-babel/issues/243#issuecomment-416757329)

```
{
  "presets": [
    ["env", {
      "modules": false
    }]
  ],
  "plugins": ["external-helpers"]
}
```

Should become

```
{
  "presets": [
    ["@babel/preset-env", {
      "modules": false
    }]
  ]
}
```

**Comment by codeBelt** [comment]
Microsoft has a great starter project for rollup:
https://github.com/Microsoft/TypeScript-Babel-Starter#using-rollup

Full project here:
https://github.com/a-tarasyuk/rollup-typescript-babel

**Comment by tmcw** [comment]
The [new babel section](http://rollupjs.org/guide/en/#babel) no longer recommends external-helpers!
