### ISSUE TITLE
Circle of broken links

### ISSUE THREAD

**Issue by callumlocke** [rollup/rollupjs.org#156]
1. Go to https://rollupjs.org/
1. In `Quick start` section, click the link to `command line interface`
1. The Wiki page says "Moved to rollupjs.org/#command-line-reference" - click this link
1. You are taken back to the same page you started on.

Same for link to `JavaScript API` in the same section.

**Comment by Rich-Harris** [comment]
whoops, thanks! fixed on the wiki, lemme know if you see any others...
