### ISSUE TITLE
REPL is broken for external imports

### ISSUE THREAD

**Issue by mourner** [rollup/rollupjs.org#167]
Steps to reproduce:

1. Go to https://rollupjs.org/repl
2. Select "External imports" example
3. Switch to `umd` on the right

Result:

![image](https://user-images.githubusercontent.com/25395/48192700-cfe76900-e348-11e8-8741-992f0833b07f.png)

If you switch to e.g. `esm` after that, it outputs a different error:

![image](https://user-images.githubusercontent.com/25395/48192756-f9a09000-e348-11e8-88a4-25c49817d3eb.png)

[REPL link](https://rollupjs.org/repl?version=0.67.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjBFWFRFUk5BTCUyMElNUE9SVFMlNUNuJTIwJTIwJTIwWW91JTIwY2FuJTIwaW1wb3J0JTIwZXh0ZXJuYWwlMjBtb2R1bGVzJTIwaW50byUyMHlvdXIlMjBidW5kbGUlMjAlRTIlODAlOTMlNUNuJTIwJTIwJTIwaXQlMjBkb2Vzbid0JTIwbWF0dGVyJTIwaWYlMjB0aGV5J3JlJTIwRVMyMDE1JTIwb3IlMjBsZWdhY3klMjAqJTJGJTVDbmltcG9ydCUyMCUyNCUyMGZyb20lMjAnanF1ZXJ5JyUzQiU1Q24lNUNuJTI0KCUyMCdib2R5JyUyMCkuaHRtbCglMjAnJTNDaDElM0VIZWxsbyUyMHdvcmxkISUzQyUyRmgxJTNFJyUyMCklM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIydW1kJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

cc @lukastaegert 
@Rich-Harris perhaps related to your recent modules refactoring?

**Comment by lukastaegert** [comment]
Seems to be fixed
