### ISSUE TITLE
REPL does not work with Rollup 1.0

### ISSUE THREAD

**Issue by Conduitry** [rollup/rollupjs.org#173]
The default example that displays for https://rollupjs.org/repl?version=1.0.0 does not work (nor does anything else that I tried).

The bundle output portion is always empty. Sometimes the error message "**TypeError:** e is undefined" is displayed in the UI.

Presumably, this is due to the new output format of `.generate()` but I have not investigated.

**Comment by lukastaegert** [comment]
Damn it, I did not check this! Unfortunately I am away from my Computer until January 2nd 😥 Any quick-fix is heartily welcome, also cc @rich-harris @guybedford

**Comment by Conduitry** [comment]
I was just taking a look at this too. It seems like that change will break now when using an old Rollup version, which would also be bad.

What I had locally and was about to suggest here was: `code: generated.output ? generated.output.find(({ isEntry }) => isEntry).code : generated.code`

It also seems like a good idea to specify `inlineDynamicImports: true` for now until multiple chunks are handled nicely.

**Comment by Rich-Harris** [comment]
I added a follow-up commit (https://github.com/rollup/rollupjs.org/commit/130c69f3fcb4da8996dc1481949010a1fc4f28ba) that makes it work in older versions too, but left multi-chunk stuff as a TODO for now

**Comment by Conduitry** [comment]
Oh, you already took care of the pre-1.0 thing it looks like.

I don't know whether `[0]` or `.find(({ isEntry }) => isEntry)` is more robust. Is the first one always the entry point?

**Comment by Rich-Harris** [comment]
I believe that's guaranteed, yeah, though @lukastaegert or @guybedford could confirm

**Comment by lukastaegert** [comment]
Yes, the first is always guaranteed to be an entry point. Thanks so much!

**Comment by Rich-Harris** [comment]
No problem — hope being AFK until the 2nd means you're taking a well-deserved break!
