### ISSUE TITLE
Direct links to URLs with fragment (#) will jump down and then back up

### ISSUE THREAD

**Issue by augbog** [rollup/rollupjs.org#182]
I started to notice this recently where if you directly navigate to a URL with a URL fragment outside of rollupjs.org i.e. https://rollupjs.org/guide/en#code-splitting

It will jump to the section immediately but then go all the way back up. On refreshing or if you are navigating within rollupjs.org, it doesn't do this.

![downandup](https://user-images.githubusercontent.com/2054339/56605223-7900e380-65b8-11e9-924b-fc11c8305e7b.gif)

**Comment by lukastaegert** [comment]
@Rich-Harris would love to have some input from you here as I think this is either a Svelte issue or an issue specific to our current Svelte setup.

**Comment by eight04** [comment]
I think this also affects the navigation menu on the first click. The second click (on a different item) works though.

**Comment by augbog** [comment]
Confirmed working thanks a lot :)
