### ISSUE TITLE
Link not https

### ISSUE THREAD

**Issue by GrosSacASac** [rollup/rollupjs.org#195]
The link of the github rollup organization is http instead of https

**Comment by Jeel5000** [comment]
> The link of the github rollup organization is http instead of https

Where?

**Comment by GrosSacASac** [comment]
https://github.com/rollup
![image](https://user-images.githubusercontent.com/5721194/180605805-423161cb-6e0d-4efd-81e5-950bf4d79531.png)

**Comment by lukastaegert** [comment]
Thanks, fixed
