### ISSUE TITLE
"Output Plugin" section code does not match the contents of the section

### ISSUE THREAD

**Issue by edelgado** [rollup/rollupjs.org#197]
I was following the helpful tutorial, and I noticed that in https://rollupjs.org/guide/en/#using-output-plugins, the contents of the section describe a minimized version of the bundle, but the code examples only show an `iife` version of the code.

No minimization happened. Or did I miss something? 😄

**Comment by lukastaegert** [comment]
Thanks for noting, I will fix it!

**Comment by lukastaegert** [comment]
Should be fixed in a few minutes.

**Comment by lukastaegert** [comment]
Fixed

**Comment by edelgado** [comment]
That was quick, thanks @lukastaegert 🙂
