### ISSUE TITLE
Auto-redirect to HTTPS

### ISSUE THREAD

**Issue by jldec** [rollup/rollupjs.org#210]
I noticed that some links to [rollupjs.org](http://rollupjs.org/) open with HTTP instead of https.
E.g. on [dev.to/pika](https://dev.to/pika/tree-shaking-without-a-bundler-here-s-how-snowpack-does-it-1fai)

Since it looks like you're using Cloudflare, maybe you could turn on auto-HTTPS redirects.

---
![Screenshot 2020-10-19 at 11 12 08](https://user-images.githubusercontent.com/849592/96432348-a86bcd00-11fc-11eb-93e2-79813b389af3.png)

**Comment by lukastaegert** [comment]
Thanks for triggering this, I am sorry this took really a long time but is fixed now :)
