### ISSUE TITLE
Repository name issue: `rollupjs.org` wasn't source code for 'http://rollupjs.org'

### ISSUE THREAD

**Issue by lyne408** [rollup/rollupjs.org#221]

**Comment by lukastaegert** [comment]
?

**Comment by lyne408** [comment]
`IDENTIFIER` tutorial.

**Comment by lyne408** [comment]
> 
> 
> ?

I suppose the repository `https://github.com/rollup/rollupjs.org` is the source code of website `http://rollupjs.org`, like the repository name style of other organizations. 
Personally.
Nothing, I've closed it.
