### ISSUE TITLE
 Domain rollupjs.org expired?

### ISSUE THREAD

**Issue by BTBMan** [rollup/rollupjs.org#242]
Can not open rollupjs.org

**Comment by AntonOfTheWoods** [comment]
http://domain-registrar.storage.googleapis.com/expired.html?rollupjs.org reports

```
rollupjs.org has expired
```

But whois reports;

```
...
Registry Expiry Date: 2022-12-23T17:07:18Z
...
```

**Comment by zhyupe** [comment]
> http://domain-registrar.storage.googleapis.com/expired.html?rollupjs.org reports
> 
> 
> 
> ```
> 
> rollupjs.org has expired
> 
> ```
> 
> 
> 
> But whois reports;
> 
> 
> 
> ```
> 
> ...
> 
> Registry Expiry Date: 2023-08-04T23:59:55Z
> 
> ...
> 
> ```
> 
> 
> 
> Maybe it's just a caching issue now.

It's expired. It's under grace period "autoRenewPeriod".

> This grace period is provided after a domain name registration period expires and is extended (renewed) automatically by the registry. If the registrar deletes the domain name during this period, the registry provides a credit to the registrar for the cost of the renewal.
