### ISSUE TITLE
Website responsive design

### ISSUE THREAD

**Issue by nickcolley** [rollup/rollupjs.org#25]
Hey coming at you from [PouchDB](http://pouchdb.com/2016/01/13/pouchdb-5.2.0-a-better-build-system-with-rollup.html), love the project!

Would you accept a pull request that makes your website work responsively, would love to contribute this. :)

**Comment by eventualbuddha** [comment]
I think I speak for Rich when I say, "Yes, please!"

**Comment by Victorystick** [comment]
Especially the guide, which I expect more people to fiddle with on their phones than they would the demo.

**Comment by nickcolley** [comment]
Sweet, I'll take this issue as 'I'm working on it' and will get something towards you folks soon. :+1:

**Comment by Rich-Harris** [comment]
Closed via #27 – many thanks
