### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by aeadedoyin** [rollup/rollupjs.org#250]
Sup friends it appears site is down.

https://isdown.me/rollupjs.org
-
![CleanShot 2024-09-20 at 10  39 41](https://github.com/user-attachments/assets/d8a4504b-89d1-4efb-97cc-fcadd3850627)

**Comment by lukastaegert** [comment]
Not sure what to make of this, and a 308 is not a page being down but a redirect. Also, it seems to be working for me. Do you have issues on your end?

**Comment by aeadedoyin** [comment]
Ah I see,
Maybe it’s the same issue, I just discovered it’s hosted on Vercel.
Vercel sites don’t work with my ISP(mtn.ng) in Nigeria

**Comment by lukastaegert** [comment]
Yes it is, and I am sorry to hear that.
