### ISSUE TITLE
missing guide sections

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollupjs.org#30]
Since #24 is closed, adding these here:
- [x] **What is Rollup?** What are JavaScript modules, what is bundling, why do we need those things? What does it _make_? (AMD/CJS/UMD/IIFE etc)
- [x] **Creating your first bundle** Prerequisites (node etc), installing globally and running on the command line
- [x] **Using config files** Where to put it, what goes in it
- [x] **Getting started with plugins** How to find them, how to use them, what they do, what order they run in
- [x] **Using Rollup with Babel** Where does one stop and the other begin? What configuration stuff do I need to know about? Having two separate `.babelrc` files (one for build tool/tests, one for source code)
- [ ] **Using Rollup with modules installed from npm** How to set it up, difference between `main` and `jsnext:main` why tree-shaking doesn't work
- [ ] **Creating sourcemaps**

Advanced guides:
- [ ] Using the JavaScript API
- [ ] Creating plugins
- [ ] Using Rollup in testing
- [ ] Using ES2015 in your build script/config file
- [ ] Distributing your library as an ES2015 module
- [ ] Bundling for node (why, when and how to do it; which dependencies should be kept external)

Misc
- [ ] Comparison with other tools
- [ ] Troubleshooting/FAQs

**Comment by jmeas** [comment]
Nice work on the site so far!

Do you plan to migrate [the API pages](https://github.com/rollup/rollup/wiki/JavaScript-API) over to the site? I might be able to help with that, if so.

**Comment by eventualbuddha** [comment]
@jmeas I would support that.

**Comment by teogeos** [comment]
The last 3 sections of the guide have been marked as 'coming soon' for 7 months. Do you plan on completing them? It would be understandable if you don't have time, but in that case it could be better to just remove them as they can give an 'incomplete' feeling to the site.

**Comment by jmeas** [comment]
> but in that case it could be better to just remove them as they can give an 'incomplete' feeling to the site.

I'd rather they open up a "here's how you can help" ticket tbqh rather than removing them entirely. If it outlined what they were going for, then I'm sure some community people would chip in

**Comment by shellscape** [comment]
Looks like the "Getting Started with Plugins" section is missing for English as well. I'll see about getting that in there.

**Comment by lukastaegert** [comment]
+1. Beyond a "getting started" section for plugins, I would suggest to move the entire section on plugin hooks from the wiki to the website: https://github.com/rollup/rollup/wiki/Plugins#creating-plugins
and reduce the plugin section in the wiki to the actual list of plugins for which it really makes sense to have a wiki.

**Comment by lukastaegert** [comment]
I believe all of this has been resolved by now or is no longer relevant
