### ISSUE TITLE
More info about available options

### ISSUE THREAD

**Issue by othree** [rollup/rollupjs.org#31]
Hi

When I read the guide about [using config files on rollupjs.org](http://rollupjs.org/guide/#using-config-files).
I don't see any information about available options.
It takes me a while to find where [it is](https://github.com/rollup/rollup/wiki/JavaScript-API#rolluprollup-options-).

I think it should have a link and give some description.
Maybe you want to have a whole new page/section about it in the future.
But a simple link can be a good temp solution and help people.

Thanks

**Comment by lukastaegert** [comment]
Should be resolved
