### ISSUE TITLE
Landing Page Demo Throws Exception in Safari 9.1.1

### ISSUE THREAD

**Issue by domchristie** [rollup/rollupjs.org#43]
The "ES2015 Modules go in … bundle comes out" demo does not render in Safari 9.1.1 (OS X 10.11.5).

> SyntaxError: Unexpected token '>'

on this line:

``` js
return new Promise( ( fulfil, reject ) => {
```

**Comment by conorcussell** [comment]
This has been fixed by this PR #41

**Comment by Victorystick** [comment]
Yes, there was a Jenkins error for that PR. Will run another build to see if it was a fluke.

**Comment by Rich-Harris** [comment]
Will close this since #41 has been merged — thank you
