### ISSUE TITLE
Broken layout on mobile?

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollupjs.org#44]
Original: https://github.com/rollup/rollup/issues/1079

Looks okay to me at most mobile screen sizes, awaiting screenshot and device details from @ssuvorov

**Comment by ssuvorov** [comment]
![img_7256](https://cloud.githubusercontent.com/assets/3448821/21533073/40d3aae8-cd57-11e6-8ffc-54319f01af85.PNG)

**Comment by Rich-Harris** [comment]
Sorry, I never got back to you on this. The site has had a fairly comprehensive overhaul since this issue was opened, and AFAICT there are no problems on mobile. If you get a chance could you see if it's still weird on your device? Thank you

**Comment by Zirro** [comment]
Just in case it could be a source of current or future issues - https://github.com/sveltejs/svelte.technology/pull/69 applies here as well.

**Comment by Rich-Harris** [comment]
@Zirro omg, thank you — I meant to fix this after that convo and I totally forgot. Fixed!
