### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollupjs.org#5]
A set of examples would go a long way towards explaining the various different import/export forms, and what Rollup actually does (especially the tree-shaking aspect). The [esperanto](http://esperantojs.org/) website has a few examples but they're all of a single module, rather than of bundles.

**Comment by Victorystick** [comment]
[TypeScript](http://www.typescriptlang.org/Playground) also has a drop-down with more complex examples. Typescript, like [esperanto](http://esperantojs.org/) and [Babel](http://babeljs.io/repl/), only concern themselves with single modules. At least we have quite a few some sources of inspiration, including [es6-module-transpiler](http://esnext.github.io/es6-module-transpiler/editor/).

**Comment by Victorystick** [comment]
Closed as of #11. Adding additional examples should be a breeze.
