### ISSUE TITLE
REPL broken in site update

### ISSUE THREAD

**Issue by hoistedvar** [rollup/rollupjs.org#52]
It appears the REPL has broken, adding or removing modules results in an error, looks like it might be the related to the of migration to svelte (in particular `src/app/Input/index.html` - in the methods it appears to think it's scope will be an array - tries to push and slice which errors out, assuming this should be the modules array)

**Comment by Rich-Harris** [comment]
Dammit, was hoping I could fix this before anyone noticed 😆 Working on it as we speak

**Comment by hoistedvar** [comment]
Haha, no worries. I thought you might have been based on some of the commit messages

**Comment by Rich-Harris** [comment]
I've rolled back to a previous version so I can be relaxed while I do surgery...

**Comment by Rich-Harris** [comment]
Ok, should be fixed now. Yell if you see anything else broken, thanks!
