### ISSUE TITLE
Invalid SSL certificate

### ISSUE THREAD

**Issue by pkoziol** [rollup/rollupjs.org#53]
Searching for "rollup js" in Google returns https://rollupjs.org/ as the first results. Opening it results in security error, because of certificate doesn't match domain name.

https://rollupjs.org/ uses certificate with Common Name = *.surge.sh
https://www.rollupjs.org/ uses certificate with Common Name = 1403.slantedhall.com

If you don't want to pay for the certificate I can recommend [Let's Encrypt](https://letsencrypt.org/) which gives certificates for free and allows to automate renewal.

**Comment by Rich-Harris** [comment]
Yeah, this is on me. The certificate isn't the problem, it's that the site is hosted on https://surge.sh, which only allows SSL with a custom domain if you pay for the premium tier — I'd basically be paying $156 a year just for this. My plan is to move it to https://zeit.co/now, which I *do* pay for and which even takes care of all the SSL stuff for you — would also mean I can rewrite it as an Express app which has certain advantages. Just need to find a spare afternoon 😬 

Not sure why Google is pointing to https. Stop it, Google!
