### ISSUE TITLE
Just copying the repl url doesn't work

### ISSUE THREAD

**Issue by micha149** [rollup/rollupjs.org#54]
**TLDR;**
This URL works: http://rollupjs.org?version=0.41.6&shareable=JTdC...
This URL fails: http://rollupjs.org/repl?version=0.41.6&shareable=JTdCJTIyb...

I created a reply demonstation for a bug a few moments ago. Just copying the url lead to a reply where not my shared content is used, but instead the default tree shaking example. If I remove the path `/repl` from the copied url, the sharing works correctly.

**Comment by Rich-Harris** [comment]
Thanks — this *should* be fixed now. I can't verify it though because the URLs above are truncated 😉

**Comment by micha149** [comment]
This urls were just for visualizing that the missing `/repl` is the difference 😉 But I can confirm: Now it works. Thanks!
