### ISSUE TITLE
document array export from config file

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollupjs.org#69]
As of 0.42, config files can export an array, and all the builds will happen in parallel. This also works with watch mode

**Comment by nathancahill** [comment]
Important to note in the docs that each config object in the array must have its own instance of any plugins used. Sharing plugin instances across configs will cause unexpected behavior.

**Comment by jhabdas** [comment]
> Sharing plugin instances across configs will cause unexpected behavior.

Could you expand on that just a little bit? I haven't seen any issues with minify or license. But I'm using them in a single import from within just one config (pre- and post-0.42 release). But these are plug-ins I need to instantiate.

**Comment by nathancahill** [comment]
Some plugins might work, others might not. I think rollup-plugin-uglify with it's custom output options was where I noticed the issue. When a plugin reads from the Rollup config object, it will overwrite that value until the last config in the array.

**Comment by jhabdas** [comment]
Thanks for expanding. I'm using the new array syntax to [output bundles](https://cdn.jsdelivr.net/npm/fetch-inject@1.7.0/dist/) and using uglifiy with harmony. Looks good to me. Not sure if our set-ups differ, but I'm using the technique left in your PR to create the minis.

**Comment by aarthi0808** [comment]
Exporting multiple config files not working for me. Please check my rollup.config.js
`import node from "rollup-plugin-node-resolve";

export default [{
  entry: "index.js",
  format: "umd",
  moduleName: "ZC",
  plugins: [node()],
  dest: "zc.js"
},{
  entry: "index.js",
  format: "umd",
  moduleName: "ZC",
  plugins: [node()],
  dest: "zc1.js"
}];`

It throws error like 

> You must specify an --input (-i) option
