### ISSUE TITLE
Format chooser should probably go on the right

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollupjs.org#8]
Partly because there's a lot more space on the right (and I wonder if there's something that should be done with that space? The right hand column is always going to be shorter than the left hand one. Maybe some blurb about what Rollup is/does), but also because the format pertains to the output rather than the input

**Comment by Victorystick** [comment]
True. I propose moving all `BundleOptions` in under `Status`, and putting the `Blurb` under the result. This lets the user see the (initially short) output first, and then read the explanation. As the output grows in length (presumably after the user read the text) it'll keep out of the way.

**Comment by Rich-Harris** [comment]
That sounds good :+1:

**Comment by Victorystick** [comment]
Any idea what it should say? Should there be separate blurbs for each example?

**Comment by Rich-Harris** [comment]
Single blurb I think – example-specific stuff probably best as inline comments, I reckon, e.g.

```js
// this function is removed, because we're not using it!
export function unused () {
  console.log( `i won't end up in the bundle' );
}
```

We could lorem ipsum it for the time being, I was thinking maybe something along the lines of

> **What is this?**
> Rollup is a next-generation JavaScript module bundler. Author your code in ES2015 modules, distribute as browser and Node.js friendly packages.
>
> **So it's like Browserify or Webpack?**
> Yes, except that the resulting bundle is smaller, because ES2015 modules are more efficient than CommonJS, and make it possible to eliminate wasted bytes with *tree-shaking*.
>
> **Tree-shaking?**
> Normally if you `require` a module, you import the whole thing. ES2015 lets you just import the bits you need, without mucking around with custom builds. It's a revolution in how we use libraries in JavaScript, and it's happening right now.
>
> **Sounds great! How do I get started?**
> Visit [github.com/rollup/rollup](https://github.com/rollup/rollup) for installation instructions and more information.

**Comment by Rich-Harris** [comment]
closing in favour of #15
